### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shdudwns** [SkyLightMCPE/SkyLightPM#2]
root@SQ-KRC-LX:~/pm# ./st*
Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
[16:45:42] [Server thread/WARNING]: Non-packaged Genisys installation detected, do not use on production.
[16:45:42] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Server::about()" (EXCEPTION) in "/src/pocketmine/Server" at line 1603
^C                                                                                 root@SQ-KRC-LX:~/pm#                                                               -----------------------------------------------------------------------------------

**Comment by shdudwns** [comment]
root@SQ-KRC-LX:~/pm# ./st*
Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
[16:45:42] [Server thread/WARNING]: Non-packaged Genisys installation detected, do not use on production.
[16:45:42] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Server::about()" (EXCEPTION) in "/src/pocketmine/Server" at line 1603
^C                                                                                 root@SQ-KRC-LX:~/pm#                                                               -----------------------------------------------------------------------------------

**Comment by shdudwns** [comment]
....

**Comment by samuelctn** [comment]
I think they are files missing from bin
we will update the php binary , don't worry.
@caspervanneck

**Comment by samuelctn** [comment]
@akaSnapy

**Comment by shdudwns** [comment]
Which driver is the fork of this driver?
@SamyR0

**Comment by samuelctn** [comment]
what do you mean ? @caspervanneck made this last commit

**Comment by shdudwns** [comment]
@SamyR0 
Genisys? Genisyspro?

**Comment by samuelctn** [comment]
I dont understand what do you want.. explain better man .

**Comment by shdudwns** [comment]
@SamyR0 
Genisys? Genisyspro?

**Comment by ghost** [comment]
@shdudwns its a fork of genisyspro

**Comment by shdudwns** [comment]
@caspervanneck hmm....

**Comment by shdudwns** [comment]
update please...
@caspervanneck
@SamyR0

**Comment by ghost** [comment]
fixt
